#!/bin/bash

scp -r -i $REMOTE_SSH_KEY_PATH \
  $REMOTE_HOST:$REMOTE_PATH/$TARGET_NAME \
  $REMOTE_HOST:$REMOTE_PATH/archive/$TARGET_NAME/

scp -r -i $REMOTE_SSH_KEY_PATH \
  $SOURCE_PATH \
  $REMOTE_HOST:$REMOTE_PATH/$TARGET_NAME
